"""Depth-compensation model loading and evaluation."""
from __future__ import annotations

import math
from typing import Optional

import numpy as np

from .config import _numpy_pickle_compat_shim, wrap_deg

def _model_type_name(model: Optional[dict]) -> str:
    if not isinstance(model, dict):
        return "none" if model is None else type(model).__name__
    mt = str(model.get("model_type", "")).strip()
    if mt:
        return mt
    if _is_rank_ratio_linear_model(model):
        return "rank_ratio_linear_depth_svd"
    if "spline" in model or "fourier" in model or "poly_coef" in model:
        return "angle_depth_error_additive_legacy"
    return "dict_unknown"


def _is_rank_ratio_linear_model(model: Optional[dict]) -> bool:
    if not isinstance(model, dict):
        return False
    if "R_reconstructed_grid" in model and "angle_grid" in model and "depth_grid" in model:
        return True
    mt = str(model.get("model_type", "")).lower()
    return ("ratio" in mt and "svd" in mt and "depth" in mt)


def _load_models(pkl_path: str) -> dict:
    import pickle

    with open(pkl_path, "rb") as f:
        _numpy_pickle_compat_shim()
        m = pickle.load(f)
    if not isinstance(m, dict):
        raise ValueError(f"Bad PKL (not dict): {pkl_path}")

    # Legacy additive compensation: comp = f(theta), z_corr = z_raw - comp.
    legacy_ok = ("spline" in m or "fourier" in m or "poly_coef" in m)

    # New model generated by plot_rank1_ratio_linear_svd.py:
    # r_hat(theta,z_raw) = h2D/h3D_proj, z_corr = z_raw * r_hat.
    rank_ratio_ok = _is_rank_ratio_linear_model(m)

    if not legacy_ok and not rank_ratio_ok:
        raise ValueError(
            f"PKL missing supported model keys: expected legacy 'spline'/'fourier'/'poly_coef' "
            f"or rank-ratio keys 'angle_grid'/'depth_grid'/'R_reconstructed_grid': {pkl_path}"
        )
    return m


def _eval_fourier(yaw_deg: float, fourier_obj: dict) -> float:
    K = int(fourier_obj.get("K", 0))
    coef = np.asarray(fourier_obj.get("coef", []), dtype=float)
    t = math.radians(float(yaw_deg) % 360.0)
    cols = [1.0]
    for k in range(1, K + 1):
        cols.extend([math.sin(k * t), math.cos(k * t)])
    cols = np.asarray(cols, dtype=float)
    n = min(coef.size, cols.size)
    return float(np.dot(cols[:n], coef[:n])) if n > 0 else 0.0


def _eval_spline(yaw_deg: float, spline_obj: dict) -> float:
    from scipy.interpolate import splev
    tck = spline_obj.get("tck", None)
    if tck is None:
        return 0.0
    return float(splev(float(yaw_deg) % 360.0, tck, ext=3))


def _eval_poly(yaw_deg: float, coef) -> float:
    try:
        return float(np.polyval(np.asarray(coef, dtype=float), float(yaw_deg) % 360.0))
    except Exception:
        return 0.0


def _angle_for_rank_ratio_grid(yaw_deg: float, angle_grid: np.ndarray) -> float:
    ag = np.asarray(angle_grid, dtype=float).reshape(-1)
    if ag.size == 0:
        return float(yaw_deg)
    amin, amax = float(np.nanmin(ag)), float(np.nanmax(ag))
    a = float(yaw_deg)

    # The rank-ratio training script is commonly used on 0..180-degree mirrored
    # vehicle-view angles.  Convert any full-circle/wrapped yaw to that domain.
    if amin >= -1e-6 and amax <= 180.0 + 1e-6:
        a = a % 360.0
        if a > 180.0:
            a = 360.0 - a
    elif amin >= -1e-6 and amax <= 360.0 + 1e-6:
        a = a % 360.0
    elif amin >= -180.0 - 1e-6 and amax <= 180.0 + 1e-6:
        a = wrap_deg(a)

    return float(np.clip(a, amin, amax))


def _predict_rank_ratio(yaw_deg: float, z_raw: float, model: dict) -> float:
    """Return r_hat(theta,z_raw) from plot_rank1_ratio_linear_svd.py output."""
    from scipy.interpolate import RegularGridInterpolator

    ag = np.asarray(model["angle_grid"], dtype=float).reshape(-1)
    dg = np.asarray(model["depth_grid"], dtype=float).reshape(-1)
    R = np.asarray(model.get("R_reconstructed_grid", model.get("R_hat")), dtype=float)

    if ag.size < 1 or dg.size < 1:
        return 1.0
    if R.shape != (ag.size, dg.size):
        R = np.asarray(R, dtype=float).reshape((ag.size, dg.size))

    a = _angle_for_rank_ratio_grid(yaw_deg, ag)
    z = float(np.clip(float(z_raw), float(dg[0]), float(dg[-1])))

    interp = RegularGridInterpolator((ag, dg), R, bounds_error=False, fill_value=None)
    ratio = float(interp(np.array([[a, z]], dtype=float))[0])
    if not np.isfinite(ratio):
        return 1.0
    return ratio


def _predict_compensation(yaw_deg: float, model: dict, z_raw: Optional[float] = None) -> float:
    """
    Return an additive compensation term compatible with the existing pipeline:
        z_corr = z_raw - comp

    Legacy pkl: comp is directly predicted in meters from yaw only.
    New rank-ratio pkl from plot_rank1_ratio_linear_svd.py:
        ratio = r_hat(theta, z_raw)
        z_corr = z_raw * ratio
        comp = z_raw - z_corr = z_raw * (1 - ratio)
    This keeps all original call sites and downstream metadata semantics intact.
    """
    if model is None:
        return 0.0

    if _is_rank_ratio_linear_model(model):
        if z_raw is None:
            return 0.0
        try:
            zr = float(z_raw)
            ratio = _predict_rank_ratio(yaw_deg, zr, model)
            return float(zr * (1.0 - ratio))
        except Exception as e:
            print(f"[comp] WARN: rank-ratio compensation failed ({e}); fallback comp=0")
            return 0.0

    try:
        if "spline" in model:
            return _eval_spline(yaw_deg, model["spline"])
    except Exception:
        pass
    try:
        if "fourier" in model:
            return _eval_fourier(yaw_deg, model["fourier"])
    except Exception:
        pass
    try:
        if "poly_coef" in model:
            return _eval_poly(yaw_deg, model["poly_coef"])
    except Exception:
        return 0.0
    return 0.0

# Public aliases with clearer names.
model_type_name = _model_type_name
load_compensation_model = _load_models
predict_compensation = _predict_compensation
